export const GET_SLIDER_HERO_ONE_REQUEST = 'GET_SLIDER_HERO_ONE_REQUEST'
export const GET_SLIDER_HERO_ONE_SUCCESS = 'GET_SLIDER_HERO_ONE_SUCCESS'
export const GET_SLIDER_HERO_ONE_FAIL = 'GET_SLIDER_HERO_ONE_FAIL'